apiVersion: batch/v1
kind: CronJob
metadata:
  name: performance-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ["wget", "http://performance-service:7007/performance"]
          restartPolicy: OnFailure
