apiVersion: v1
kind: Service
metadata:
  name: performance-service
spec:
  selector:
    app: performance-svc
  ports:
    - protocol: TCP
      port: 7007            
      targetPort: 7007     
  type: ClusterIP   